language: python
sudo: false
os:
  - linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r dev-requirements.txt

script:
  - "django-admin test test_twitter_clone --settings twitter_clone.settings --pythonpath twitter_clone"
